enum BlockShapes {
    HAT = 'hat',
    BOOLEAN = 'boolean',
    REPORTER = 'reporter',
    C = 'c',
    CAP = 'cap',
    STACK = 'stack',
}

enum BlockOpcodes {
    CONTROL_FOREVER = 'control_forever',
    CONTROL_REPEAT = 'control_repeat',
    CONTROL_IF = 'control_if',
    CONTROL_IF_ELSE = 'control_if_else',
    CONTROL_STOP = 'control_stop',
    CONTROL_WAIT = 'control_wait',
    CONTROL_WAIT_UNTIL = 'control_wait_until',
    CONTROL_REPEAT_UNTIL = 'control_repeat_until',
    CONTROL_WHILE = 'control_while',
    CONTROL_FOR_EACH = 'control_for_each',
    CONTROL_START_AS_CLONE = 'control_start_as_clone',
    CONTROL_CREATE_CLONE_OF_MENU = 'control_create_clone_of_menu',
    CONTROL_CREATE_CLONE_OF = 'control_create_clone_of',
    CONTROL_DELETE_THIS_CLONE = 'control_delete_this_clone',
    CONTROL_GET_COUNTER = 'control_get_counter',
    CONTROL_INCR_COUNTER = 'control_incr_counter',
    CONTROL_CLEAR_COUNTER = 'control_clear_counter',
    CONTROL_ALL_AT_ONCE = 'control_all_at_once',
    DATA_VARIABLE = 'data_variable',
    DATA_SETVARIABLETO = 'data_setvariableto',
    DATA_CHANGEVARIABLEBY = 'data_changevariableby',
    DATA_SHOWVARIABLE = 'data_showvariable',
    DATA_HIDEVARIABLE = 'data_hidevariable',
    DATA_LISTCONTENTS = 'data_listcontents',
    DATA_LISTINDEXALL = 'data_listindexall',
    DATA_LISTINDEXRANDOM = 'data_listindexrandom',
    DATA_ADDTOLIST = 'data_addtolist',
    DATA_DELETEOFLIST = 'data_deleteoflist',
    DATA_DELETEALLOFLIST = 'data_deletealloflist',
    DATA_INSERTATLIST = 'data_insertatalist',
    DATA_REPLACEITEMOFLIST = 'data_replaceitemoflist',
    DATA_ITEMOFLIST = 'data_itemoflist',
    DATA_ITEMNUMOFLIST = 'data_itemnumoflist',
    DATA_LENGTHOFLIST = 'data_lengthoflist',
    DATA_LISTCONTAINSITEM = 'data_listcontainsitem',
    DATA_SHOWLIST = 'data_showlist',
    DATA_HIDELIST = 'data_hideslist',
    EVENT_WHENTOUCHINGOBJECT = 'event_whentouchingobject',
    EVENT_TOUCHINGOBJECTMENU = 'event_touchingobjectmenu',
    EVENT_WHENFLAGCLICKED = 'event_whenflagclicked',
    EVENT_WHENTHISSPRITECLICKED = 'event_whenthisspriteclicked',
    EVENT_WHENSTAGECLICKED = 'event_whenstageclicked',
    EVENT_WHENBROADCASTRECEIVED = 'event_whenbroadcastreceived',
    EVENT_WHENBACKDROPSWITCHESTO = 'event_whenbackdropswitchesto',
    EVENT_WHENGREATERTHAN = 'event_whengreaterthan',
    EVENT_BROADCAST_MENU = 'event_broadcast_menu',
    EVENT_BROADCAST = 'event_broadcast',
    EVENT_BROADCASTANDWAIT = 'event_broadcastandwait',
    EVENT_WHENKEYPRESSED = 'event_whenkeypressed',
}

export const BlockOpcodeToShape = {
    [BlockOpcodes.CONTROL_FOREVER]: BlockShapes.CAP,
    [BlockOpcodes.CONTROL_REPEAT]: BlockShapes.C,
    [BlockOpcodes.CONTROL_IF]: BlockShapes.C,
    [BlockOpcodes.CONTROL_IF_ELSE]: BlockShapes.C,
    [BlockOpcodes.CONTROL_STOP]: BlockShapes.CAP,
    [BlockOpcodes.CONTROL_WAIT]: BlockShapes.STACK,
    [BlockOpcodes.CONTROL_WAIT_UNTIL]: BlockShapes.C,
    [BlockOpcodes.CONTROL_REPEAT_UNTIL]: BlockShapes.C,
    [BlockOpcodes.CONTROL_WHILE]: BlockShapes.C,
    [BlockOpcodes.CONTROL_FOR_EACH]: BlockShapes.C,
    [BlockOpcodes.CONTROL_START_AS_CLONE]: BlockShapes.HAT,
    [BlockOpcodes.CONTROL_CREATE_CLONE_OF_MENU]: BlockShapes.STACK,
    [BlockOpcodes.CONTROL_CREATE_CLONE_OF]: BlockShapes.STACK,
    [BlockOpcodes.CONTROL_DELETE_THIS_CLONE]: BlockShapes.CAP,
    [BlockOpcodes.CONTROL_GET_COUNTER]: BlockShapes.STACK,
    [BlockOpcodes.CONTROL_INCR_COUNTER]: BlockShapes.C,
    [BlockOpcodes.CONTROL_CLEAR_COUNTER]: BlockShapes.C,
    [BlockOpcodes.CONTROL_ALL_AT_ONCE]: BlockShapes.C,
    [BlockOpcodes.DATA_VARIABLE]: BlockShapes.REPORTER,
    [BlockOpcodes.DATA_SETVARIABLETO]: BlockShapes.STACK,
    [BlockOpcodes.DATA_CHANGEVARIABLEBY]: BlockShapes.STACK,
    [BlockOpcodes.DATA_SHOWVARIABLE]: BlockShapes.STACK,
    [BlockOpcodes.DATA_HIDEVARIABLE]: BlockShapes.STACK,
    [BlockOpcodes.DATA_LISTCONTENTS]: BlockShapes.REPORTER,
    [BlockOpcodes.DATA_LISTINDEXALL]: BlockShapes.REPORTER,
    [BlockOpcodes.DATA_LISTINDEXRANDOM]: BlockShapes.REPORTER,
    [BlockOpcodes.DATA_ADDTOLIST]: BlockShapes.STACK,
    [BlockOpcodes.DATA_DELETEOFLIST]: BlockShapes.STACK,
    [BlockOpcodes.DATA_DELETEALLOFLIST]: BlockShapes.STACK,
    [BlockOpcodes.DATA_INSERTATLIST]: BlockShapes.STACK,
    [BlockOpcodes.DATA_REPLACEITEMOFLIST]: BlockShapes.STACK,
    [BlockOpcodes.DATA_ITEMOFLIST]: BlockShapes.REPORTER,
    [BlockOpcodes.DATA_ITEMNUMOFLIST]: BlockShapes.REPORTER,
    [BlockOpcodes.DATA_LENGTHOFLIST]: BlockShapes.REPORTER,
    [BlockOpcodes.DATA_LISTCONTAINSITEM]: BlockShapes.BOOLEAN,
    [BlockOpcodes.DATA_SHOWLIST]: BlockShapes.STACK,
    [BlockOpcodes.DATA_HIDELIST]: BlockShapes.STACK,
    [BlockOpcodes.EVENT_WHENTOUCHINGOBJECT]: BlockShapes.HAT,
    [BlockOpcodes.EVENT_TOUCHINGOBJECTMENU]: BlockShapes.REPORTER,
    [BlockOpcodes.EVENT_WHENFLAGCLICKED]: BlockShapes.HAT,
    [BlockOpcodes.EVENT_WHENTHISSPRITECLICKED]: BlockShapes.HAT,
    [BlockOpcodes.EVENT_WHENSTAGECLICKED]: BlockShapes.HAT,
    [BlockOpcodes.EVENT_WHENBROADCASTRECEIVED]: BlockShapes.HAT,
    [BlockOpcodes.EVENT_WHENBACKDROPSWITCHESTO]: BlockShapes.HAT,
    [BlockOpcodes.EVENT_WHENGREATERTHAN]: BlockShapes.HAT,
    [BlockOpcodes.EVENT_BROADCAST_MENU]: BlockShapes.REPORTER,
    [BlockOpcodes.EVENT_BROADCAST]: BlockShapes.STACK,
    [BlockOpcodes.EVENT_BROADCASTANDWAIT]: BlockShapes.STACK,
    [BlockOpcodes.EVENT_WHENKEYPRESSED]: BlockShapes.HAT,
}